url: "https://E4S-Project.github.io"
title: "E4S - An HPC-AI Software Ecosystem for Science"
subtitle: "Advancing Science through Trusted Software"
description: "Curated HPC-AI scientific libraries and tools for advanced scientific computing applications."
baseurl: ""

# Use Minimal Mistakes as a remote theme
remote_theme: "mmistakes/minimal-mistakes"

# Required plugins for Minimal Mistakes on GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

repository: "E4S-Project/E4S-Project.github.io"
repo_host: https://github.com
github_username: "maherou"

minimal_mistakes_skin: "air"

atom_feed:
  hide: true

future: true

logo: /assets/images/E4S-no-background.png
og_image: /assets/images/E4S-no-background.png
